/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { StakedEscrow } from "./StakedEscrow";
export * as factories from "./factories";
export { StakedEscrow__factory } from "./factories/StakedEscrow__factory";
